### ISSUE TITLE
Fatal error: Uncaught Zend\Db\Adapter\Exception\InvalidArgumentException: DriverInterface expected...

### ISSUE THREAD

**Issue by DonatoDeluxe** [tkrebs/ep3-hs#3]
Hallo
Nachdem ich lokal ein neues Projekt eingerichtet habe, bekomme folgende Fehlermeldung wenn ich "http://localhost.repos/ep3-hs/public/setup.php" aufrufe.
-------------------------------------------------------------------------------------------------------------------

```
Fatal error:
Uncaught Zend\Db\Adapter\Exception\InvalidArgumentException: DriverInterface expected in D:\Repositories\ep3-hs\vendor\zendframework\zendframework\library\Zend\Db\Adapter\Adapter.php:304
Stack trace:
#0 D:\Repositories\ep3-hs\vendor\zendframework\zendframework\library\Zend\Db\Adapter\Adapter.php(80): Zend\Db\Adapter\Adapter->createDriver(Array)
#1 D:\Repositories\ep3-hs\vendor\zendframework\zendframework\library\Zend\Db\Adapter\AdapterServiceFactory.php(26): Zend\Db\Adapter\Adapter->__construct(Array)
#2 [internal function]: Zend\Db\Adapter\AdapterServiceFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zenddbadapterad...', 'Zend\\Db\\Adapter...')
#3 D:\Repositories\ep3-hs\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'zenddbadapterad...', 'Zend\\Db\\Adapter...')
#4 D:\Repositories\ep3-hs\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(1097): Zend\Serv in D:\Repositories\ep3-hs\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php on line 946
```

-------------------------------------------------------------------------------------------------------------------

Folgende Arbeitsschritte hatte ich durchgeführt:

1. klonen des Projekts von "https://github.com/tkrebs/ep3-hs" - master
2. composer install auf dem Projektverzeichnis durchgeführt
3. lokal eine neue DB erstellt mit dem namen "bookingsystem"
4. unter /config/autoload/ "local.php.dist" auf "local.php" umbennent und inhaltlich wie folgt angepasst:
-------------------------------------------------------------------------------------------------------------------
```
ini_set('date.timezone', 'Europe/Zurich');

return array(
    'mail' => array(
        'type' => 'sendmail',
        'address' => 'xxxxx.xxxxx@xxxxx.ch',
    ),
    'db' => array(
        'driver' => 'Mysql',
        'hostname' => 'localhost',
        'database' => 'bookingsystem',
        'username' => 'bookingsys',
        'password' => 'bookingsys-password',
        'port' => null,
    ),
    'i18n' => array(
        'locale' => 'de-CH',
        'currency' => 'CHF',
    ),
);
```
-------------------------------------------------------------------------------------------------------------------
5. "http://localhost.repos/ep3-hs/public/setup.php" aufgerufen.

Ich benutze XAMPP v.3.2.2 (Server Software: Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.10) auf einem Windows10 Betriebssystem.

Wäre sehr froh um Hilfe danke.

**Comment by tkrebs** [comment]
Was mir spontan auffällt: Versuch mal

```php
'db' => array(
    'driver' => 'mysql',
```

klein zu schreiben.

**Comment by DonatoDeluxe** [comment]
leider auch keinen Erfolg...

**Comment by DonatoDeluxe** [comment]
Der einzige Schritt den ich "übersprungen" habe, war Schritt 2. der Installation.

> 2. Enable (recursively) UNIX write permission for
>    - data/cache/
>    - data/log/
>    - data/session/
>    - public/docs-client/upload/
>    - public/imgs-client/upload/

Ich war/bin mir nicht sicher, ob dieser Schritt auf Windows 10 notwendig ist und wie man diesen ausführen muss.

**Comment by tkrebs** [comment]
Das ist richtig so, unter Windows gibt es diese Berechtigungen nicht.

Versuch sonst mal diese Syntax:

```php
'db' => array(
    'user' => '?',
    'pass' => '?',
    'dsn' => 'mysql:dbname=?;host=127.0.0.1',
),

**Comment by DonatoDeluxe** [comment]
Danke für die Rückmeldung

Dies war mein erster Versuch hat jedoch auch nicht funktioniert.
Inzwischen konnte ich das Problem beheben.
Es lag an den User-Berechtigungen von der Datenbank....
Nach dem anpassen der Berechtigungen des Users, den ich beim "local.php"-File angegeben habe, konnte ich das Setup durchführen und die Datenbank-Tabellen generieren.

Jetzt komme ich zwar auf die Hauptseite jedoch bekomme ich einen 404 sobald ich auf "Anmelden" klicke....

![image](https://user-images.githubusercontent.com/32309242/49160863-fdac4600-f327-11e8-9a40-2b09f42f90ea.png)

Lass mich wissen, falls ich hierfür ein neues Issue erstellen soll.
